import Head from "next/head";
import Landingpage from "../public/landing-page.svg";
import WImage from "../components/Home/WImage";
import Typed from "typed.js";

import { useEffect, useRef } from "react";
import Link from "next/link";

export default function Home() {
  const el = useRef(null);

  useEffect(() => {
    const typed = new Typed(el.current, {
      strings: [
        "Instagram",
        "Group Chats",
        "Snapchat",
        "Twitter",
        "WhatsApp",
        "Messenger",
        "Discord",
      ],
      startDelay: 300,
      typeSpeed: 100,
      backSpeed: 100,
      backDelay: 100,
      loop: true,
    });

    return () => {
      typed.destroy();
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-screen bg-grad">
          <div className="container flex flex-col-reverse justify-center h-full p-10 md:p-20 px-10 md:px-20 mx-auto md:grid md:grid-cols-2 md:gap-x-8">
            <div className="max-h-[60%] sm:max-h[80%] md:max-h-[100%] relative flex-grow mb-5 drop-shadow-2xl md:mx-4 w-full">
              <div className="relative h-full">
                <WImage src={Landingpage} />
              </div>
              <div className="flex justify-center mt-12 md:hidden">
                <Link href={"/create"}>
                  <a
                    type="button"
                    className="inline self-center  py-4 px-8 md:px-12 mb-8 text-base md:text-md lg:text-xl create-event font-semibold text-white"
                  >
                    🎉 Create my event
                  </a>
                </Link>
              </div>
            </div>

            <div className="text-center md:text-right md:self-center lg:mr-24 sm:pb-8">
              <span className="block text-3xl font-bold lg:pb-4 md:text-4xl lg:text-5xl xl:text-6xl text-envited-400">
                <p>Imagine if&nbsp;</p>
                <span className="typed-content" ref={el}></span>
                &nbsp;
                <span className="block md:hidden pb-2">had events</span>
                <span className="hidden md:inline">had</span>
                <span className="hidden md:block ">events.</span>
                {/* <p>events.</p> */}
              </span>
              <p className="mb-5 lg:mb-12 text-base text-envited-400 md:text-xl lg:text-3xl">
                Easily host and share events with your friends across any social
                media.{" "}
              </p>
              <Link href={"/create"}>
                <a
                  type="button"
                  className="hidden md:inline py-4 px-12 mb-8 text-base md:text-md lg:text-xl create-event font-semibold text-white"
                >
                  🎉 Create my event
                </a>
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
